// Thin typed fetch wrapper over the backend API.
//
// Types come from ./schema.d.ts (generated by `make frontend-gen-api` from the
// FastAPI OpenAPI spec). This module owns the cross-cutting concerns — Bearer
// auth injection, JSON encode/decode, and error normalization — so feature
// hooks (Tasks 4-6) just call `apiRequest<T>` with the response type they want,
// indexed off `Schemas`.
//
// Paths are relative: same-origin in production (the backend serves the SPA)
// and proxied to the backend by the Vite dev server in development.
import type { components, paths } from "./schema";

import { getApiKey } from "./keyStore";

export type { components, paths };

/** All response/request models from the OpenAPI spec, e.g. `Schemas["EventResponse"]`. */
export type Schemas = components["schemas"];

/** A non-2xx response (or a transport failure) surfaced as a typed error. */
export class ApiError extends Error {
  readonly status: number;
  readonly detail: unknown;

  constructor(status: number, message: string, detail: unknown = undefined) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.detail = detail;
  }
}

interface RequestOptions {
  method?: "GET" | "POST" | "PATCH" | "DELETE";
  json?: unknown;
  signal?: AbortSignal;
}

/**
 * Issue one request and return the decoded JSON body typed as `T`.
 *
 * Attaches `Authorization: Bearer <key>` when a key is configured, sends/parses
 * JSON, and throws {@link ApiError} on any non-2xx response. A `204` resolves to
 * `undefined`.
 */
export async function apiRequest<T>(path: string, options: RequestOptions = {}): Promise<T> {
  const headers = new Headers({ Accept: "application/json" });

  const key = getApiKey();
  if (key) {
    headers.set("Authorization", `Bearer ${key}`);
  }

  const init: RequestInit = { method: options.method ?? "GET", headers };
  if (options.signal) {
    init.signal = options.signal;
  }
  if (options.json !== undefined) {
    headers.set("Content-Type", "application/json");
    init.body = JSON.stringify(options.json);
  }

  const response = await fetch(path, init);

  if (response.status === 204) {
    return undefined as T;
  }

  const payload = await parseBody(response);
  if (!response.ok) {
    throw new ApiError(response.status, errorMessage(response.status, payload), payload);
  }
  return payload as T;
}

/** GET /health — unauthenticated; doubles as a connectivity probe. */
export function getHealth(): Promise<Schemas["HealthResponse"]> {
  return apiRequest<Schemas["HealthResponse"]>("/health");
}

async function parseBody(response: Response): Promise<unknown> {
  const text = await response.text();
  if (!text) {
    return undefined;
  }
  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.includes("application/json")) {
    return JSON.parse(text);
  }
  return text;
}

function errorMessage(status: number, payload: unknown): string {
  if (status === 401) {
    return "API key missing or invalid";
  }
  return detailOf(payload) ?? `Request failed with status ${status}`;
}

function detailOf(payload: unknown): string | null {
  if (payload && typeof payload === "object" && "detail" in payload) {
    const detail = (payload as { detail: unknown }).detail;
    if (typeof detail === "string") {
      return detail;
    }
  }
  return null;
}
