/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/admin/ingest/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Recent ingestion runs
     * @description Return the most-recent ingestion_runs rows (newest first), capped by 'limit'.
     */
    get: operations["admin_ingest_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/ingest/trigger": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Trigger a poll_usgs run
     * @description Enqueues poll_usgs on Celery and returns the new task id. Run outcome surfaces in /status.
     */
    post: operations["admin_ingest_trigger"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/locks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all endpoint locks
     * @description Return every row in quake.endpoint_locks.
     */
    get: operations["admin_locks_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/locks/{lock_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Set an endpoint lock
     * @description Flip is_locked=true on a seeded lock_name. Body carries optional locked_by/reason.
     */
    post: operations["admin_locks_set"];
    /**
     * Clear an endpoint lock
     * @description Flip is_locked=false and null out locked_by / locked_at / reason.
     */
    delete: operations["admin_locks_clear"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/alerts/filters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List this key's alert filters
     * @description Return every quake.alert_filters row owned by the authenticated key.
     */
    get: operations["alerts_filters_list"];
    put?: never;
    /**
     * Create a new alert filter
     * @description Persist a filter scoped to the authenticated key. Body validates as AlertFilter — bbox XOR center+radius, optionally combined with min_magnitude. An empty filter (no predicates) is rejected with 422.
     */
    post: operations["alerts_filters_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/alerts/filters/{filter_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete one alert filter
     * @description Remove a filter owned by the authenticated key. Unknown ids return 404.
     */
    delete: operations["alerts_filters_delete"];
    options?: never;
    head?: never;
    /**
     * Replace one alert filter
     * @description Full-replacement update of one filter's fields. The filter must belong to the authenticated key; unknown ids and cross-key ids both return 404.
     */
    patch: operations["alerts_filters_update"];
    trace?: never;
  };
  "/alerts/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Server-Sent-Events stream of matching events
     * @description Open a long-lived SSE connection. Filters configured on the authenticated key via /alerts/filters are snapshotted at connect time; matched events arrive as `event: alert` frames with the AlertEnvelope JSON. Returns 400 if no filters are configured (so the stream isn't opened for a key that can't receive anything).
     */
    get: operations["alerts_stream"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/env": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Running environment summary
     * @description Returns ENVIRONMENT, APPLICATION_NAME, and the running version.
     */
    get: operations["main_env"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Query earthquakes
     * @description Filter earthquakes by any combination of near=lat,lon + radius_km, min_magnitude, since (timezone-aware), and limit. All filters are optional and combinable.
     */
    get: operations["events_query"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/events/recent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Recent earthquakes
     * @description Last N events, newest first.
     */
    get: operations["events_recent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Service health check
     * @description Liveness probe returning service identity and version.
     */
    get: operations["main_health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Prometheus metrics
     * @description Prometheus text exposition for every metric on the default registry.
     */
    get: operations["main_metrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AlertFilter
     * @description One filter row, as the client supplies it.
     *
     *     The shape is *bbox XOR center+radius*, optionally combined with a
     *     ``min_magnitude`` floor. At least one predicate must be set —
     *     an entirely empty filter would match every event and is rejected
     *     so the operator can't accidentally fan out the firehose to a key.
     */
    AlertFilter: {
      /** Bbox Max Lat */
      bbox_max_lat?: number | null;
      /** Bbox Max Lon */
      bbox_max_lon?: number | null;
      /** Bbox Min Lat */
      bbox_min_lat?: number | null;
      /** Bbox Min Lon */
      bbox_min_lon?: number | null;
      /** Center Lat */
      center_lat?: number | null;
      /** Center Lon */
      center_lon?: number | null;
      /** Min Magnitude */
      min_magnitude?: number | null;
      /** Radius Km */
      radius_km?: number | null;
    };
    /**
     * AlertFilterResponse
     * @description Public representation of one ``quake.alert_filters`` row.
     */
    AlertFilterResponse: {
      /** Api Key Id */
      api_key_id: number;
      /** Bbox Max Lat */
      bbox_max_lat?: number | null;
      /** Bbox Max Lon */
      bbox_max_lon?: number | null;
      /** Bbox Min Lat */
      bbox_min_lat?: number | null;
      /** Bbox Min Lon */
      bbox_min_lon?: number | null;
      /** Center Lat */
      center_lat?: number | null;
      /** Center Lon */
      center_lon?: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Id */
      id: number;
      /** Min Magnitude */
      min_magnitude?: number | null;
      /** Radius Km */
      radius_km?: number | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * AlertFiltersListResponse
     * @description Envelope wrapping the caller's filters plus the row count.
     *
     *     The envelope (rather than a bare list) leaves room for future
     *     additions — paging cursors, totals, query echo — without breaking
     *     existing clients. Mirrors :class:`quake.api.events.models.EventsListResponse`.
     */
    AlertFiltersListResponse: {
      /** Count */
      count: number;
      /** Filters */
      filters: components["schemas"]["AlertFilterResponse"][];
    };
    /** EnvResponse */
    EnvResponse: {
      /** Application Name */
      application_name: string;
      /** Environment */
      environment: string;
      /** Version */
      version: string;
    };
    /**
     * EventResponse
     * @description Public-API representation of one ``quake.events`` row.
     *
     *     ``from_attributes=True`` lets ``EventResponse.model_validate(row)``
     *     consume a :class:`database.models.EventRow` directly.
     */
    EventResponse: {
      /** Depth Km */
      depth_km?: number | null;
      /** Event Id */
      event_id: string;
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
      /** Magnitude */
      magnitude: number;
      /** Magnitude Type */
      magnitude_type?: string | null;
      /** Place */
      place?: string | null;
      /** Status */
      status?: string | null;
      /**
       * Time
       * Format: date-time
       */
      time: string;
      /** Tsunami */
      tsunami: boolean;
      /** Url */
      url?: string | null;
    };
    /**
     * EventsListResponse
     * @description Envelope wrapping a list of events plus its size.
     *
     *     The envelope (rather than a bare list) leaves room for future
     *     additions — paging cursors, totals, query echo — without breaking
     *     existing clients.
     */
    EventsListResponse: {
      /** Count */
      count: number;
      /** Events */
      events: components["schemas"]["EventResponse"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Service */
      service: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /**
     * IngestRunResponse
     * @description Public representation of one ``quake.ingestion_runs`` row.
     */
    IngestRunResponse: {
      /** Error */
      error?: string | null;
      /** Finished At */
      finished_at?: string | null;
      /** Id */
      id: number;
      /** Inserted Count */
      inserted_count: number;
      /** Revision Count */
      revision_count: number;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Updated Count */
      updated_count: number;
    };
    /**
     * IngestStatusResponse
     * @description Envelope wrapping the most-recent ingestion runs + their count.
     */
    IngestStatusResponse: {
      /** Count */
      count: number;
      /** Runs */
      runs: components["schemas"]["IngestRunResponse"][];
    };
    /**
     * LockResponse
     * @description Public representation of one ``quake.endpoint_locks`` row.
     */
    LockResponse: {
      /** Is Locked */
      is_locked: boolean;
      /** Lock Name */
      lock_name: string;
      /** Locked At */
      locked_at?: string | null;
      /** Locked By */
      locked_by?: string | null;
      /** Reason */
      reason?: string | null;
    };
    /**
     * LocksListResponse
     * @description Envelope wrapping the locks list + its size.
     */
    LocksListResponse: {
      /** Count */
      count: number;
      /** Locks */
      locks: components["schemas"]["LockResponse"][];
    };
    /**
     * SetLockRequest
     * @description Body for ``POST /admin/locks/{lock_name}``.
     *
     *     Both fields are optional metadata. The lock itself flips on via the
     *     POST regardless of what's in the body.
     */
    SetLockRequest: {
      /** Locked By */
      locked_by?: string | null;
      /** Reason */
      reason?: string | null;
    };
    /**
     * TriggerResponse
     * @description Reply from ``POST /admin/ingest/trigger``.
     *
     *     The task runs out-of-band on a Celery worker; this response only
     *     confirms enqueue. ``GET /admin/ingest/status`` is where the actual
     *     outcome shows up.
     */
    TriggerResponse: {
      /**
       * Queued At
       * Format: date-time
       */
      queued_at: string;
      /** Task Id */
      task_id: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  admin_ingest_status: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_ingest_trigger: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TriggerResponse"];
        };
      };
    };
  };
  admin_locks_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocksListResponse"];
        };
      };
    };
  };
  admin_locks_set: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lock_name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetLockRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LockResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_locks_clear: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lock_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LockResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  alerts_filters_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlertFiltersListResponse"];
        };
      };
    };
  };
  alerts_filters_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AlertFilter"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlertFilterResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  alerts_filters_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filter_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  alerts_filters_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filter_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AlertFilter"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlertFilterResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  alerts_stream: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  main_env: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EnvResponse"];
        };
      };
    };
  };
  events_query: {
    parameters: {
      query?: {
        near?: string | null;
        radius_km?: number | null;
        min_magnitude?: number | null;
        since?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventsListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  events_recent: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventsListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  main_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  main_metrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
