"""Re-order and de-noise ``database/schema.sql`` in place.

``dbmate dump`` shells out to ``pg_dump``, which emits a usable but noisy
file: leading ``SET``s, ``\\restrict``/``\\unrestrict`` meta-commands,
COMMENTs, and blocks in an order driven by pg_dump's own logic rather
than what a human reader wants. This module:

1. Strips the noise — preamble ``SET``s, ``\\restrict``/``\\unrestrict``,
   ``COMMENT ON`` blocks, and inline ``SET default_*`` lines that pg_dump
   sprinkles between blocks.
2. Re-parses remaining content into ``-- Name: …; Type: …; Schema: …``
   blocks (the pg_dump idiom), sorts them by category, and re-emits with
   pg_dump-compatible headers.
3. Preserves the dbmate ``INSERT INTO public.schema_migrations`` footer
   verbatim so future ``dbmate`` invocations still see the applied
   migrations.

The output is **idempotent**: re-running against an already-prettified
file produces identical bytes, so ``make db-schema`` is safe to invoke
back-to-back (verified in the acceptance criteria of PLAN.md Task 8).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Final

SCHEMA_PATH: Final = Path(__file__).resolve().parent / "schema.sql"

# Category ordering — lower comes first.
_TYPE_ORDER: Final[dict[str, int]] = {
    "SCHEMA": 1,
    "EXTENSION": 2,
    "FUNCTION": 3,
    "SEQUENCE": 4,
    "TABLE": 5,
    "SEQUENCE OWNED BY": 6,
    "DEFAULT": 7,
    "CONSTRAINT": 8,
    "FK CONSTRAINT": 9,
    "INDEX": 10,
    "TRIGGER": 11,
}
_FALLBACK_ORDER: Final = 99

# Block types we always strip.
_DROP_TYPES: Final = frozenset({"COMMENT"})

# Splits the dump into header-marked blocks. The header is the pg_dump
# triple-line: "--\n-- Name: X; Type: T; Schema: S; Owner: -\n--".
_HEADER_RE: Final = re.compile(
    r"^--\n-- Name: (?P<name>.+?); Type: (?P<type>[A-Z ]+); Schema: (?P<schema>.+?); Owner: .+?\n--\n",
    re.MULTILINE,
)

# Marks the start of the dbmate migrations footer. Everything from this
# marker to EOF is preserved verbatim.
_MIGRATIONS_MARKER: Final = "-- Dbmate schema migrations"


def _split_main_and_migrations(text: str) -> tuple[str, str]:
    """Split off the dbmate migrations footer (everything from its marker on)."""
    idx = text.find(_MIGRATIONS_MARKER)
    if idx == -1:
        return text, ""
    return text[:idx], text[idx:].rstrip() + "\n"


def _parse_blocks(text: str) -> list[tuple[str, str, str, str]]:
    """Return ``[(type, schema, name, body)]`` for every pg_dump block in ``text``."""
    matches = list(_HEADER_RE.finditer(text))
    blocks: list[tuple[str, str, str, str]] = []
    for i, match in enumerate(matches):
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end].strip()
        blocks.append((match["type"], match["schema"], match["name"], body))
    return blocks


def _order_key(block: tuple[str, str, str, str]) -> tuple[int, int, str, str]:
    """Sort by (type bucket, schema bucket, schema name, object name)."""
    type_, schema, name, _ = block
    type_pri = _TYPE_ORDER.get(type_, _FALLBACK_ORDER)
    # quake before public (dbmate bookkeeping) within each type.
    schema_pri = 0 if schema == "quake" else 1
    return (type_pri, schema_pri, schema, name)


def _render(blocks: list[tuple[str, str, str, str]]) -> str:
    """Emit blocks with pg_dump-compatible headers so re-parsing is idempotent."""
    parts: list[str] = []
    for type_, schema, name, body in blocks:
        if type_ in _DROP_TYPES:
            continue
        header = f"--\n-- Name: {name}; Type: {type_}; Schema: {schema}; Owner: -\n--\n"
        parts.append(f"{header}\n{body}\n")
    return "\n\n".join(parts)


def prettify(text: str) -> str:
    """Pure transform: take a raw ``dbmate dump`` string, return the prettified version."""
    main, migrations_footer = _split_main_and_migrations(text)
    blocks = _parse_blocks(main)
    blocks.sort(key=_order_key)
    body = _render(blocks)
    preamble = (
        "-- This file is auto-generated by `make db-schema`.\n"
        "-- Run `make db-schema` after migrations land to refresh.\n"
        "-- DO NOT EDIT by hand — changes will be overwritten.\n"
    )
    output = preamble + "\n\n" + body
    if migrations_footer:
        output = output.rstrip() + "\n\n\n" + migrations_footer
    return output.rstrip() + "\n"


def main() -> None:
    if not SCHEMA_PATH.exists():
        raise SystemExit(f"{SCHEMA_PATH} not found — run `dbmate dump` first.")
    raw = SCHEMA_PATH.read_text()
    SCHEMA_PATH.write_text(prettify(raw))


if __name__ == "__main__":
    main()
